### PR TITLE
subclasses of LineItem deleted, renamed package 'product' to 'products'

### PR DESCRIPTION
**Pull request by joaquin-rojkind**

### CODE REVIEW

**Comment by joaquin-rojkind** [comment]
[Implement remove products](https://trello.com/c/tQn7gzz3/24-implement-remove-products)

**Comment by joaquin-rojkind** [comment]
[Implement remove seats](https://trello.com/c/kCaiUq8U/25-implement-remove-seats)

**Comment by nicolas-antomarioni** [comment]
LGTM

**Comment by juan-blasco** [comment]
LGTM!

**Pull request merged**
