### PR TITLE
Created factory bean for service initialization

### PR DESCRIPTION
**Pull request by juan-blasco**

### CODE REVIEW

**Comment by juan-blasco** [comment]
@ezequielmatalon updated PR

**Comment by nicolas-antomarioni** [comment]
[Create factory bean for services](https://trello.com/c/yyBuVKgz/12-create-factory-bean-for-services)

**Comment by nicolas-antomarioni** [comment]
[Create factory bean for services](https://trello.com/c/yyBuVKgz/12-create-factory-bean-for-services)

**Comment by nicolas-antomarioni** [comment]
[Rename AutodeskService to AutodeskRestService](https://trello.com/c/eMwdyrC1/11-rename-autodeskservice-to-autodeskrestservice)

**Pull request merged**
